# Generated by Django 3.2.4 on 2021-06-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nashsshubapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='name',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='cost',
            field=models.CharField(max_length=50),
        ),
    ]
