# Generated by Django 3.2.4 on 2021-06-09 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nashsshubapi', '0003_auto_20210609_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='bookmarks',
        ),
    ]
